name: Export Conda Environments from Lockfiles

on:
  workflow_dispatch:

jobs:
  export-env-macos:
    runs-on: macos-latest
    steps:
      - name: Download env file
        run: |
          curl -sLO https://raw.githubusercontent.com/atharva-2001/tardisbase/env-benchmark/env.yml

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest

      - name: Create environment from env file
        shell: bash -l {0}
        run: |
          mamba env create -f env.yml -n tardis-bench -y

      - name: Export environment
        shell: bash -l {0}
        run: |
          conda activate tardis-bench
          conda env export --no-builds > env-bench-macos.yml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-bench-macos
          path: env-bench-macos.yml

  export-env-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Download env file
        run: |
          curl -sLO https://raw.githubusercontent.com/atharva-2001/tardisbase/env-benchmark/env.yml

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest

      - name: Create environment from env file
        shell: bash -l {0}
        run: |
          mamba env create -f env.yml -n tardis-bench -y

      - name: Export environment
        shell: bash -l {0}
        run: |
          conda activate tardis-bench
          conda env export --no-builds > env-bench-linux.yml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-bench-linux
          path: env-bench-linux.yml
